CREATE PROCEDURE sp_ebiz_obtener_registros_sapdocprovision 
				 @tabla varchar(50),
				 @estado varchar(2),
				 @id INT,
				 @tabla varchar(50),
                 @estado varchar(2)

SET @SelectString = 'SELECT BUKRS,LIFNR,UMSKS,UMSKZ,AUGDT,AUGBL,ZUONR,' +
    'GJAHR,BELNR,BUZEI,BUDAT,BLDAT,CPUDT,WAERS,XBLNR,BLART,MONAT,BSCHL,ZUMSK,SHKZG,GSBER,MWSKZ,' +
    'DMBTR,WRBTR,MWSTS,WMWST,BDIFF,BDIF2,SGTXT,SAKNR,HKONT,FKONT,ZFBDT,ZTERM,ZBD1T,ZBD2T,ZBD3T,' +
    'ZBD1P,ZBD2P,SKFBT,SKNTO,WSKTO,ZLSCH,ZLSPR,ZBFIX,HBKID,BVTYP,REBZG,REBZJ,REBZZ,LANDL,QSSKZ,QSSHB,' +
    'QBSHB,BSTAT,REBZT,QSZNR,QSFBT,XREF1,XREF2,PSWSL,PSWBT,EMPFB,XREF3,XPYPR,KIDNO,PYCUR,PYAMT,FKBER,AUGGJ,ESTADO,' +
    'FAEDT,FWBAS,FWSTE,KBETR,BANKS,BANKL,ZZDET,ZZTAG,STCD1,STCEG,IDSAPDOC_PROVISION,KUNNR,BANKN,INTERVALOFECHA,NAME1 FROM '+
	'dbo.SAPDOC_PROVISION_'+@tabla+;
	
	IF @estado
	' WHERE (ESTADO=? or ESTADO=?) AND BUKRS=? AND INTERVALOFECHA=? ';


	 