CONNECT TO MONDEV;
CREATE TABLE MONITOR.CONTROL (
 IDCONTROL INTEGER  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE )  ,
 FLAGPROCESO SMALLINT  NOT NULL , 
 TIPO VARCHAR (5)  NOT NULL ,
 FECHAREGISTRO TIMESTAMP  WITH DEFAULT 'CURRENT TIMESTAMP' ,
 MENSAJE VARCHAR (1024)  ,
 CONSTRAINT CC1371500375465 PRIMARY KEY ( IDCONTROL)  ) IN TS_MONITOR 
  PARTITION BY RANGE(IDCONTROL)
    (STARTING FROM (MINVALUE) ENDING AT (MAXVALUE) EVERY (1000) );
CONNECT RESET;

CONNECT TO MONDEV;
CREATE TABLE MONITOR.CONTROL ( IDCONTROL INTEGER  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) ,
 FLAGPROCESO SMALLINT  NOT NULL ,
 TIPO VARCHAR (5)  NOT NULL ,
 FECHAREGISTRO TIMESTAMP  NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
 MENSAJE VARCHAR (3000)  NOT NULL  ,
 CONSTRAINT CC1371504045247 PRIMARY KEY ( IDCONTROL)  ) IN TS_MONITOR ;
CONNECT RESET;


CONNECT TO MONDEV;
CREATE TABLE MONITOR.M_ERROR ( IDMERROR INTEGER  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) , IDCONTROL INTEGER  NOT NULL , IDMACCION INTEGER  NOT NULL , IDCLIENTE INTEGER  NOT NULL , IDERRORCOMPONENTE INTEGER  NOT NULL , NUMERODOCUMENTO VARCHAR (50)  NOT NULL , RUCSOCIEDAD VARCHAR (15)  NOT NULL , RUCPROVEEDOR VARCHAR (15)  NOT NULL , DESCRIPCION VARCHAR (300)  WITH DEFAULT '' , FECHAERROR TIMESTAMP  NOT NULL , ESTADO SMALLINT  NOT NULL  WITH DEFAULT 0  , CONSTRAINT CC1371506136851 PRIMARY KEY ( IDMERROR) , CONSTRAINT CC1371506163715 FOREIGN KEY (IDCONTROL) REFERENCES MONITOR.CONTROL (IDCONTROL)  ON DELETE NO ACTION ON UPDATE NO ACTION NOT ENFORCED  ENABLE QUERY OPTIMIZATION , CONSTRAINT CC1371506201919 FOREIGN KEY (IDMACCION) REFERENCES MONITOR.M_ACCION (IDMACCION)  ON DELETE NO ACTION ON UPDATE NO ACTION NOT ENFORCED  ENABLE QUERY OPTIMIZATION , CONSTRAINT CC1371506215663 FOREIGN KEY (IDCLIENTE) REFERENCES MONITOR.CLIENTE (IDCLIENTE)  ON DELETE NO ACTION ON UPDATE NO ACTION NOT ENFORCED  ENABLE QUERY OPTIMIZATION , CONSTRAINT CC1371506236130 FOREIGN KEY (IDERRORCOMPONENTE) REFERENCES MONITOR.ERRORCOMPONENTE (IDERRORCOMPONENTE)  ON DELETE NO ACTION ON UPDATE NO ACTION NOT ENFORCED  ENABLE QUERY OPTIMIZATION  ) IN TS_MONITOR ;
CONNECT RESET;
